name: "on merge: build the main branch"

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build an image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push latest image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: buildme/Dockerfile
          push: true
          tags: sshaman1101/fooer:latest
