name: "Manually: build testing images"

on: workflow_dispatch

jobs:
  build_image:
    name: "build image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cleanup the ref name
        # turns "refs/heads/fix/the-short-name" into
        # the docker-tag-friendly "fix-the-short-name".
        run: echo "GITHUB_REF_SHORT=$(echo $GITHUB_REF | sed -e 's/refs\/heads\///' -e 's/\//-/')" >> $GITHUB_ENV

      - name: login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push latest image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: buildme/Dockerfile
          push: true
          tags: sshaman1101/fooer:${{ env.GITHUB_REF_SHORT }}
